# Generated by Django 5.0.4 on 2024-04-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_by', to='userprofile.userprofile'),
        ),
    ]
